### ISSUE TITLE
Plot runtime results

### ISSUE THREAD

**Issue by ocramz** [haskell-perf/graphs#5] opened 2018-07-06 13:18 UTC
It would be great if you could plot the results, rather than presenting tables of numbers. Thanks!

**Comment by snowleopard** [comment] 2018-07-06 15:46
I fully support this -- it would be great to have, say, a bar chart showing timing for the largest benchmark across different algorithms. Here is [an example](https://habrastorage.org/getpro/habr/post_images/2fe/126/a6e/2fe126a6ed00fb984b3d43c8c413746d.png), although the horizontal axis here shows different sizes, whereas we need different algorithms.

**Comment by nobrakal** [comment] 2018-07-06 18:02
Yeah this looks great ! Thanks for the suggestion @ocramz :)

**Comment by nobrakal** [comment] 2018-07-09 12:13
Ok I have implemented a first version that is producing a bar chart per benchmarked function using the `Chart` library.

I hesitate on what to do to "group" charts (putting several results on the same file, like the example of @snowleopard ):

* Group them per "category" (graph modification/graph inspection/... or vertex-work/edge-work/...)
* Group them on user demand (will make the command line very long)
* Not group them

Any idea ?

**Comment by snowleopard** [comment] 2018-07-09 17:16
@nobrakal This is what I had in mind:
* Three charts: time, memory, time (creation + algorithm).
* In each chart, you have several groups of bars -- one group per algorithm (`hasVertex`, `hasEdge`, etc.). Groups have textual labels.
* In each group, you have bars shown next to each other -- one bar per library (`containers`, `fgl`, etc.). Bars are distinguished by colour, with a colour legend given on the chart.
* In each bar, you accumulate the running time of the two (`mesh` + `clique`) largest (`1000`) benchmarks, stacking these two "sub-bars". The two sub-bars could be identified simply by their order (`mesh` at the bottom, `clique` on top -- which could be explained in the legend too).

I think this would be very convenient.

**Comment by nobrakal** [comment] 2018-07-09 21:16
Thanks for the detailed plan, seems very good to me. I will try to implement it soon !

**Comment by snowleopard** [comment] 2018-07-13 12:20
Cool :)

> I have chose to display benchs on separated graphs, for scale reason

I think having a separate scale per benchmark does not look too bad and is actually quite useful.

> Again for scale reason, I have used a logarithmic scale,

Yep, this makes sense.

> This makes hard to "stack" bars (make subs bars per graph type), since it is very difficult to read.

If you switch to lighter colours then the black border will be sufficiently visible to separate multiple bars (of the same colour) in one stack. I think it's interesting to see how `mesh` and `clique` graphs compare.

**Comment by nobrakal** [comment] 2018-07-13 13:04
Thanks for the comment !

> If you switch to lighter colours then the black border will be sufficiently visible to separate multiple bars (of the same color) in one stack. I think it's interesting to see how mesh and clique graphs compare.

Even with these colors, it is readable. The problem is the logarithmic scale ^^. I find reading stacked bars with such a scale rather complicated... 

You are right, the difference is quite interesting. I think two groups per algorithms (one for mesh time and one for clique time) can be great.

**Comment by snowleopard** [comment] 2018-07-13 14:40
> The problem is the logarithmic scale

Ah, I didn't realise this :) Well, you could split the stack proportionally, i.e. not in relation to the logarithmic scale -- the log scale would only be used for the sum of two values. But I can see that this may be confusing. 

Separating into different charts make this less helpful.

**Comment by nobrakal** [comment] 2018-07-13 16:49
Might be really strange, I think this can add more confusion

> Separating into different charts make this less helpful.

Using the same scale, why it is less helpful ? You can quickly view if there is a big difference (for example with `transpose` containers and alga are equivalents on Mesh, but alga become 3 time faster on Clique). This can feel weird with proportionally stacked bars, but the difference will be clear using two groups.

Maybe it is better to have stacked bars for a trained eye, but for someone just wanting results, I think it is more clear with two groups :) (the logarithmic scale can already introduce some confusion)

**Comment by nobrakal** [comment] 2018-07-14 13:12
Just generated it (with graphs with 100 vertices, either it will have take some hours to run...). I will make a better version (with bigger graphs) when re-releasing results at the end :)

I forgot to add `hasSelfLoop` equivalent for others libraries , so alga is alone ^^.

![results](https://user-images.githubusercontent.com/6417395/42724730-0320fbba-8778-11e8-93c0-1fcc27495abf.png)


@ocramz You were right, results are clearer now !

**Comment by ocramz** [comment] 2018-07-14 13:17
Very nice ! 👏

**Comment by snowleopard** [comment] 2018-07-14 14:42
@nobrakal This is awesome! 

I think it would be useful to provide implementations of missing functions, so that we always have 4 bars in these charts. Otherwise, we have an incomplete picture, and it may be non-obvious to reconstruct missing values in one's head. Of course, the library authors would be welcome to modify the implementations if they like to improve reported results.

**Comment by nobrakal** [comment] 2018-07-14 15:11
> an error bar to these histograms ? If that's not too much work.

Might be interesting yes, I will invetigate

> I think it would be useful to provide implementations of missing functions

Someone on reddit suggested to add information about why some benchs are 'missing', it is on my todo list ^^.
The problem is that some functions are meaningless or impossible to implement for some libraries. For example:
* Containers's graphs are constructed using a "range", they have all the vertices in this range, and that all. So you cannot implement `addVertex` or `hasVertex` and `vertexCount` does not have sense.
* Do we really want to see results of `mergeContext` for Alga ? Is it making sense ?
* Algorithms are not often implemented, but I can try to add them. But like you say it will likely be a bad implementation, and it can be strange to have a very fast library with some bad results due to my errors.

In all cases it definitely need some documentation, and I will add them to the "standard" output in markdown. I don't know if there is a pretty way to do this in the chart...

**Comment by snowleopard** [comment] 2018-07-14 15:44
> So you cannot implement `addVertex` or `hasVertex` and `vertexCount` does not have sense

Why? I think they all can be implemented quite sensibly: `addVertex` will recreate the array allocating a spot for a new vertex (yes, that's expensive but that's what you have to do if you are using `containers`), `hasVertex` will just do a range comparison, and `vertexCount` will return the range size.

> Do we really want to see results of `mergeContext` for Alga ? Is it making sense ?

Well, `mergeContext` is not a common graph operation, so I think it's OK to omit it. But `addVertex` is fundamental for many use cases.

> it can be strange to have a very fast library with some bad results due to my errors.

I see nothing strange: if a library does not provide an implementation, users will need to implement it on their own and they might make an error. This is an open repository and library authors can always fix a mistake if there is one.

**Comment by nobrakal** [comment] 2018-07-15 15:49
> Why? I think they all can be implemented quite sensibly

Ok, I will add them then :) They seemed a bit strange to me.

> I see nothing strange

It fits me, you are right !

I will add missing functions soon

**Comment by nobrakal** [comment] 2018-07-23 16:58
Missing functions are added, except `removeVertex` for Containers, because it would "split" the array...

@ocramz : Took me some time (a good part of the day) to figure how to implement error bars on regular bars.

I just added a working version to `master`. Here is a sample with `equality` and `hasVertex`. Is this what you had in mind ?

![results](https://user-images.githubusercontent.com/6417395/43091410-520fc33a-8eaa-11e8-90fd-e287ae5619a4.png)

**Comment by snowleopard** [comment] 2018-07-23 17:16
> Missing functions are added, except removeVertex for Containers, because it would "split" the array...

@nobrakal You can still implement it by relabelling vertices so that there is no gap. For example, if you remove vertex `x` from a graph, you'll need to relabel vertex `v` as follows:

```haskell
relabel :: Int -> Int -> Int
relabel x v | v < x     = v
            | otherwise = v - 1
```

**Comment by ocramz** [comment] 2018-07-23 17:31
@nobrakal Great job! This gives the idea that runtime differences are significant, though it's still hard to make clear statements on relative performance due to the interaction of GHC garbage collector, OS scheduler etc. How many replicates did you use to compute the error bars?

**Comment by nobrakal** [comment] 2018-07-23 19:50
@snowleopard  Is that solution really a `removeVertex` ? At the end, we obtain an isomorphic graphs but we have changed the vertices set. When I am doing a `removeVertex 42`, it feels strange to have again vertex numbered `42` after... The main problem for me is that this will not be the same function than the three others libraries (which are effectively removing the vertex without relabeling the rest of the vertices).

@ocramz Yeah ! This is a number directly extracted from `Criterion` so it depends on how many iterations `Criterion` ran (I use the default here. From memory, it is based on a time limit rather than a number of iteration). More precisely, the errors bars are made from an average between different values of standard deviation extracted from criterion benchmarks (for example for `hasVertex`, I test for three vertex positioned differently and a vertex outside the graph). I get the values for the bars the same way.

**Comment by nobrakal** [comment] 2018-07-23 20:29
> so I don't see why removeVertex is more special.

Here we need to rename on part of the graph :) But you are right, if someone want to really remove a vertex in `Data.Graph`, let us show him what it implies ^^.

**Comment by nobrakal** [comment] 2018-08-12 09:57
I am closing this, everything was corrected. New results have just been merged in `master` :)

**Closed by nobrakal** 2018-08-12 09:57 UTC
